version: '2'
services:
  OpenTSDB:
    image: cloudflare/opentsdb
    environment:
      TSD_CONF_tsd__core__auto_create_metrics: 'true'
      TSD_CONF_tsd__http__request__enable_chunked: 'true'
      TSD_CONF_tsd__http__request__max_chunk: '33554432'
      TSD_CONF_tsd__network__port: '4242'
      TSD_CONF_tsd__storage__fix_duplicates: 'true'
      TSD_CONF_tsd__storage__hbase__zk_quorum: zk1:2181,zk2:2181,zk3:2181
    stdin_open: true
    entrypoint:
    - /run.sh
    external_links:
    - zookeeper/zk3:zk3
    - zookeeper/zk2:zk2
    - zookeeper/zk1:zk1
    tty: true
    ports:
    - 4242:4242/tcp
    labels:
      io.rancher.container.pull_image: always
