zk1:
  image: confluentinc/cp-zookeeper
  environment:
    ZOOKEEPER_SERVER_ID: 1
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 30000
    ZOOKEEPER_INIT_LIMIT: 5
    ZOOKEEPER_SYNC_LIMIT: 2
    ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  labels:
   - "io.rancher.scheduler.affinity:container_label_ne=io.rancher.stack.name=$${stack_name}"
zk2:
  image: confluentinc/cp-zookeeper
  environment:
    ZOOKEEPER_SERVER_ID: 2
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 30000
    ZOOKEEPER_INIT_LIMIT: 5
    ZOOKEEPER_SYNC_LIMIT: 2
    ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  labels:
   - "io.rancher.scheduler.affinity:container_label_ne=io.rancher.stack.name=$${stack_name}"
zk3:
  image: confluentinc/cp-zookeeper
  environment:
    ZOOKEEPER_SERVER_ID: 3
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 30000
    ZOOKEEPER_INIT_LIMIT: 5
    ZOOKEEPER_SYNC_LIMIT: 2
    ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  labels:
   - "io.rancher.scheduler.affinity:container_label_ne=io.rancher.stack.name=$${stack_name}"
